////////////////////////////////
//filename:DeviceToUiHandler.cpp
//description:UI层服务端接受文件
//data:2022/09/18 21:15:39
//author:wocattree
////////////////////////////////

// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DeviceToUiHandler.h"

DeviceToUiHandler::DeviceToUiHandler()
{
    // Your initialization goes here
}

void DeviceToUiHandler::ReportDeviceTemps(const MonitorTemps& monitortemps)
{
    // Your implementation goes here
    //printf("ReportDeviceTemps\n");
    //printf("服务端接收到数据，收到的数据是：\n");
    std::for_each(monitortemps.Temps.begin(), monitortemps.Temps.end(), [](const auto& i) {std::cout << i << " "; });
}