////////////////////////////////
//filename:DeviceToUiHandler.cpp
//description:UI层服务端接受文件
//data:2022/09/18 21:15:39
//author:wocattree
////////////////////////////////

// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DeviceToUiHandler.h"


DeviceToUiHandler::DeviceToUiHandler()
{
    // Your initialization goes here
}

void DeviceToUiHandler::ReportDeviceTemps(const MonitorTemps& monitortemps)
{
    // Your implementation goes here
    std::for_each(monitortemps.Temps.begin(), monitortemps.Temps.end(), [](const auto& i) {std::cout << i << " "; });

    //接收到消息，转发到状态机，是什么消息做什么处理todo

    //存入数据库
    auto& m_pDeviceDB = DeviceDB::GetInstance();

    std::string Sqlword = "insert into d_environment values( now(),";
    std::string temp = std::to_string(monitortemps.Temps[0]) + ",";
    std::string humi = std::to_string(monitortemps.Temps[1]) + ")";
    Sqlword = Sqlword + temp + humi;
    m_pDeviceDB.Implement(Sqlword.c_str());
}