/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ServerToUi_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




MonitorTemps::~MonitorTemps() noexcept {
}


void MonitorTemps::__set_Temps(const std::vector<double> & val) {
  this->Temps = val;
}
std::ostream& operator<<(std::ostream& out, const MonitorTemps& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MonitorTemps::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->Temps.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->Temps.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readDouble(this->Temps[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.Temps = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t MonitorTemps::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MonitorTemps");

  xfer += oprot->writeFieldBegin("Temps", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_DOUBLE, static_cast<uint32_t>(this->Temps.size()));
    std::vector<double> ::const_iterator _iter5;
    for (_iter5 = this->Temps.begin(); _iter5 != this->Temps.end(); ++_iter5)
    {
      xfer += oprot->writeDouble((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MonitorTemps &a, MonitorTemps &b) {
  using ::std::swap;
  swap(a.Temps, b.Temps);
  swap(a.__isset, b.__isset);
}

MonitorTemps::MonitorTemps(const MonitorTemps& other6) {
  Temps = other6.Temps;
  __isset = other6.__isset;
}
MonitorTemps& MonitorTemps::operator=(const MonitorTemps& other7) {
  Temps = other7.Temps;
  __isset = other7.__isset;
  return *this;
}
void MonitorTemps::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MonitorTemps(";
  out << "Temps=" << to_string(Temps);
  out << ")";
}


